### PR TITLE
Set correct build url based on if its a dev of pr image.

### LINKED ISSUE #57: [BUG] incorrect ghcr link for lsiodev and lspipepr images
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the image built is a dev or pr image, the link to the image tag in the ci report is incorrect.

For instance, the amd64 pr image for jellyfin is currently linked to: `https://ghcr.io/lspipepr/jellyfin:amd64-nightly-2024091605ubu2404-pkg-a1d32746-dev-9f97c8782aab3a8c6b5c3b1209ab0e2caf79c146-pr-266`
but it should be `https://ghcr.io/linuxserver/lspipepr-jellyfin:amd64-nightly-2024091605ubu2404-pkg-a1d32746-dev-9f97c8782aab3a8c6b5c3b1209ab0e2caf79c146-pr-266`

Here's the ci results page: https://ci-tests.linuxserver.io/lspipepr/jellyfin/nightly-2024091605ubu2404-pkg-a1d32746-dev-9f97c8782aab3a8c6b5c3b1209ab0e2caf79c146-pr-266/index.html

### Expected Behavior

For ghcr, the link format for pr images should be `https://ghcr.io/linuxserver/lspipepr-<container-name>:<image-tag>`
and for dev images, it should be `https://ghcr.io/linuxserver/lsiodev-<container-name>:<image-tag>`

I believe the issue stemmed from converting these links over from docker hub links, where we used separate orgs for `lsiodev` and `lspipepr` whereas on ghcr, we use the same org `linuxserver` for everything, but we prepend the image names with either `lsiodev` or `lspipepr`

### Steps To Reproduce

1. Go to https://ci-tests.linuxserver.io/lspipepr/jellyfin/nightly-2024091605ubu2404-pkg-a1d32746-dev-9f97c8782aab3a8c6b5c3b1209ab0e2caf79c146-pr-266/index.html
2. Click on the image tag under `PASS` or `FAIL`

### Environment

```markdown
N/A
```

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

### PR DESCRIPTION
**Pull request by GilbN**
- Set correct build url based on if it's a dev of pr image.
- Add test for build_url function.

lsiodev test: ~~https://gilbnlsio2.s3.us-east-1.amazonaws.com/lsiodev/lidarr/2.3.3.4204-pkg-891c8a1a-dev-39ebb48d3454c6b0326510ac1176c93625dd9d71/index.html~~

lspipepr test: ~~https://gilbnlsio2.s3.us-east-1.amazonaws.com/lspipepr/lidarr/2.3.3.4204-pkg-891c8a1a-dev-39ebb48d3454c6b0326510ac1176c93625dd9d71-pr-107/index.html~~

linuxserver test: ~~https://gilbnlsio2.s3.us-east-1.amazonaws.com/linuxserver/lidarr/2.5.3.4341-ls10/index.html~~

https://gilbnlsio2.s3.us-east-1.amazonaws.com/lspipepr/lidarr/2.3.3.4204-pkg-891c8a1a-dev-39ebb48d3454c6b0326510ac1176c93625dd9d71-pr-107/index.html

### CODE REVIEW

**Comment by thespad** [comment]
The link is correct but the text isn't going to match. Perhaps instead of:

`Test Results lsiodev/lidarr:2.3.3.4204-pkg-891c8a1a-dev-39ebb48d3454c6b0326510ac1176c93625dd9d71`

Just do something like:

`Test Results lidarr:2.3.3.4204-pkg-891c8a1a-dev-39ebb48d3454c6b0326510ac1176c93625dd9d71`

And then similarly just the image tag in the per-arch summaries?

We know if it's live/dev/pr based on the tag format anyway and can just prepend `lsiodev/` or `ghcr.io/linuxserver/` etc. if we need to pull them.

**Comment by aptalca** [comment]
Perhaps we can change the text to match the ghcr image and tag

The text and link used to be for docker hub images. We changed the link to ghcr, but the text is still docker hub. Perhaps we match them again?

**Comment by thespad** [comment]
As we've pretty much moved to GHCR as the primary option across the board then yeah, we might as well change the text to match

**Comment by GilbN** [comment]
👍🏻

**Comment by GilbN** [comment]
New test with some report changes. 

https://gilbnlsio2.s3.us-east-1.amazonaws.com/lspipepr/lidarr/2.3.3.4204-pkg-891c8a1a-dev-39ebb48d3454c6b0326510ac1176c93625dd9d71-pr-107/index.html


[dfcf34a](https://github.com/linuxserver/docker-ci/pull/58/commits/dfcf34a15067ea43f9a310f8bef5d331786d3788)
- Fixes link name.
- Add more information to build info section in the report. Center and split the top report headers

@thespad @aptalca

**Review by aptalca — APPROVED** [review]

**Pull request merged**
